name: flutter_application_1
version: 1.0.0+1
publish_to: none
description: A new Flutter project.
environment:
  sdk: ">=3.1.3 <4.0.0"

dependencies:
  line_awesome_flutter: ^2.0.0
  cupertino_icons: ^1.0.2
  get: 4.6.6
  hexcolor: ^3.0.1
  image_picker: ^1.0.4
  image: ^3.0.1
  flutter:
    sdk: flutter
  webview_flutter: ^4.4.1
  http: ^1.1.0
  firebase_auth: ^4.12.1
  firebase_core: ^2.22.0
  firebase_messaging: ^14.7.3
  flutter_local_notifications: ^16.1.0
  shared_preferences: ^2.2.0


dev_dependencies:
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true

  assets:
    - assets/images/
