// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDWOPB6Ijq1Iy6XtRDXR7aR04H121ob90Q',
    appId: '1:312190583960:web:190893991151cb0a3fbced',
    messagingSenderId: '312190583960',
    projectId: 'hospitalapp-2ae28',
    authDomain: 'hospitalapp-2ae28.firebaseapp.com',
    storageBucket: 'hospitalapp-2ae28.appspot.com',
    measurementId: 'G-2YKZJT423C',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyA4Xbj6kx0cRCInpQjWqzrxNrE8rNxxKNM',
    appId: '1:312190583960:android:b9dd8cf483b64c493fbced',
    messagingSenderId: '312190583960',
    projectId: 'hospitalapp-2ae28',
    storageBucket: 'hospitalapp-2ae28.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAXnR7VfVel24F8ZFegtC8tNGvNZRciXUY',
    appId: '1:312190583960:ios:c08fc8e69d36555e3fbced',
    messagingSenderId: '312190583960',
    projectId: 'hospitalapp-2ae28',
    storageBucket: 'hospitalapp-2ae28.appspot.com',
    iosClientId: '312190583960-lldka090dq4bc5db35klna81u0c7s4l0.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAXnR7VfVel24F8ZFegtC8tNGvNZRciXUY',
    appId: '1:312190583960:ios:fc3dba3c207234273fbced',
    messagingSenderId: '312190583960',
    projectId: 'hospitalapp-2ae28',
    storageBucket: 'hospitalapp-2ae28.appspot.com',
    iosClientId: '312190583960-8110qdjc23n02befm3334udf3314gtu9.apps.googleusercontent.com',
    iosBundleId: 'com.example.flutterApplication1.RunnerTests',
  );
}
